#!/usr/bin/env lua
-- mpdf
-- pops up a zenity file-selection to ask
-- a file to open with  mupdf

local command = 'mupdf'

function exec(cmd)
  local file = io.popen(cmd)
  return file:read('a'):sub(1, -2) -- strip '\n'
end

-- TODO: escape special chars
local file = exec('zenity --file-selection --filename="$HOME/"')
file = file:gsub('"', '\\%1')
os.execute(command .. ' "' .. file .. '"')
