#!/usr/bin/env lua
-- mpdf
-- pops up a zenity file-selection to ask
-- for a file to open with zathura

local command = 'zathura'

function exec(cmd)
  local file = io.popen(cmd)
  return file:read('*a'):sub(1, -2) -- strip '\n'
end

local file = exec('zenity --file-selection --filename="$HOME/"')
file = file:gsub('"', '\\%1')
os.execute(command .. ' "' .. file .. '"')
